server:
  port: 8080

spring:
  application:
    name: voting-service
  jpa:
    open-in-view: true

configs:
  threads:
    default: 10
    max: 100
  kafka:
    group-id: 'voting.service.${spring.profiles.active}'
    concurrency: 5
    topics:
      voting-registration:
        name: 'voting.registration.${spring.profiles.active}'
        ttl-in-days: 1
    topic-props:
      - name: ${configs.kafka.topics.voting-registration.name}
        partitions: 3
        replication-factory: 1